---
permalink: protect-sce/task_reseed_a_replica_using_powershell_cmdlets_for_exchange_database.html 
sidebar: sidebar 
keywords: SnapCenter plug-in for Exchange Server 
summary: Vous pouvez utiliser les applets de commande PowerShell pour restaurer une réplique défectueuse en utilisant la copie la plus récente sur le même hôte ou la copie la plus récente depuis un autre hôte. 
---
= Réamorçage d'une réplique à l'aide des applets de commande PowerShell pour la base de données Exchange
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser les applets de commande PowerShell pour restaurer une réplique défectueuse en utilisant la copie la plus récente sur le même hôte ou la copie la plus récente depuis un autre hôte.

Les informations relatives aux paramètres pouvant être utilisés avec la cmdlet et leurs descriptions peuvent être obtenues en exécutant _get-Help nom_commande_. Vous pouvez également vous reporter à la https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guide de référence de l'applet de commande du logiciel SnapCenter"^].

.Étapes
. Lancez une session de connexion avec le serveur SnapCenter pour un utilisateur spécifié à l'aide de `Open-SmConnection` l'applet de commande.
+
[listing]
----
Open-smconnection  -SMSbaseurl  https:\\snapctr.demo.netapp.com:8146/
----
. Réamorcer la base de données à l'aide de l' `reseed-SmDagReplicaCopy` applet de commande.
+
Cet exemple replace la copie échouée de la base de données appelée execdb sur l'hôte "mva-rx200.netapp.com" en utilisant la dernière sauvegarde sur cet hôte.

+
[listing]
----
reseed-SmDagReplicaCopy -ReplicaHost "mva-rx200.netapp.com" -Database execdb
----
+
Cet exemple replace la copie échouée de la base de données appelée execdb en utilisant la dernière sauvegarde de la base de données (production/copie) sur un autre hôte "mva-rx201.netapp.com."

+
[listing]
----
reseed-SmDagReplicaCopy -ReplicaHost "mva-rx200.netapp.com" -Database  execdb -BackupHost "mva-rx201.netapp.com"
----

